name: "Validate compatiblity with metamask"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "16"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests
        id: tests
        run: xvfb-run --auto-servernum yarn run test
        env:
          METAMASK_VERSION: 'latest'

      - name: Check if issue already exists
        if: failure()
        uses: nickderobertis/check-if-issue-exists-action@8edfc8560578e80eb6061565e5359d85d5d63b74
        id: issue
        with:
          repo: ChainSafe/dappeteer
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "question, bug"
          title: "Problem with MetaMask version ${{ steps.tests.outputs.version }}"

      - name: Submit issue
        if: failure() && steps.issue.outputs.exists == 'false'
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "BeroBurny, "
          labels: "question, bug"
          title: "Problem with MetaMask version ${{ steps.tests.outputs.version }}"
          body: |-
            Seems that `MetaMask` version `${{ steps.tests.outputs.version }}` is not working currect with current version of `Dappeteer`
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
